name: Create Archive
on:
  push:
    tags:
      - 'zip-v*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: setup node
        uses: actions/setup-node@v3.2.0
        with:
          node-version: 18
          cache: 'yarn'
      - run: corepack enable
      - name: install app dependencies and build it
        run: yarn && yarn build
      - name: Zip Release
        uses: TheDoctor0/zip-release@0.6.2
        with:
          type: 'zip'
          path: 'dist'
          filename: 'release.zip'
      - name: Create Release
        uses: ncipollo/release-action@v1.11.1
        with:
          artifacts: "release.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
